### ISSUE TITLE
CSS - Page footer

### ISSUE THREAD

**Issue by Joshowens16** [2208-Capstone-Team-2/codenames#112]
![Screen Shot 2023-01-28 at 11 08 51 AM](https://user-images.githubusercontent.com/79232977/215286476-596ba817-0130-4463-bcf7-2570ad73cdf7.png)
Here is the codenames footer, could be a simple footer that has our names, github link etc

**Comment by rosalie0** [comment]
I'm putting this as 1.5 Tier because i think this would be some nice CSS!
